---

application:
  audience: ${env.AUTH0_AUDIENCE}
  client-origin-url: ${env.CLIENT_ORIGIN_URL}
  stripe-api-key: ${env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
  stripe-secret-key: ${env.NEXT_PUBLIC_STRIPE_SECRET_KEY}
server:
  error:
    whitelabel:
      enabled: false
  port: ${env.PORT}

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${env.AUTH0_DOMAIN}/
  web:
    resources:
      add-mappings: false

...
